#!/usr/bin/env python3
"""Converts the ISBN range table into the plain format the app reads.

The source is ISBN International's public RangeMessage.xml file:
    https://www.isbn-international.org/export_rangemessage.xml

The app has no network access, so the table is bundled; refresh it now and then
as new publisher ranges open:

    python3 tools/isbn_ranges.py            # download and write
    python3 tools/isbn_ranges.py file.xml   # write from a local file

Output (core/src/main/resources/.../isbn-ranges.txt), one group per line:

    978-975<TAB>Türkiye<TAB>0000000-0199999:5,0200000-2399999:2,...

Ranges apply to the seven digits after the group prefix; the number after ':' is
the length of the publisher element (0 = range not yet defined).
"""
import sys
import urllib.request
import xml.etree.ElementTree as ET
from pathlib import Path

URL = "https://www.isbn-international.org/export_rangemessage.xml"
OUT = Path(__file__).resolve().parent.parent / "core/src/main/resources/com/aripd/kodokur/core/isbn-ranges.txt"


def main() -> None:
    if len(sys.argv) > 1:
        data = Path(sys.argv[1]).read_bytes()
    else:
        with urllib.request.urlopen(URL, timeout=60) as r:
            data = r.read()
    root = ET.fromstring(data)
    date = (root.findtext("MessageDate") or "").strip()
    serial = (root.findtext("MessageSerialNumber") or "").strip()

    lines = [f"# ISBN International RangeMessage · {date} · {serial}",
             "# Generated by tools/isbn_ranges.py; do not edit by hand."]
    for group in root.iter("Group"):
        prefix = group.findtext("Prefix").strip()
        agency = " ".join(group.findtext("Agency").split())
        rules = []
        for rule in group.iter("Rule"):
            rng = rule.findtext("Range").strip()
            length = rule.findtext("Length").strip()
            lo, hi = rng.split("-")
            if len(lo) != 7 or len(hi) != 7:
                sys.exit(f"Unexpected range format: {prefix} {rng}")
            rules.append(f"{rng}:{length}")
        if "\t" in agency or not rules:
            sys.exit(f"Malformed group: {prefix}")
        lines.append(f"{prefix}\t{agency}\t{','.join(rules)}")

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"{OUT.relative_to(Path.cwd()) if OUT.is_relative_to(Path.cwd()) else OUT}: "
          f"{len(lines) - 2} groups, {date}")


if __name__ == "__main__":
    main()
